name: Check Azure Boards Work Item

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-work-item:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Verificar se o PR está vinculado a um Work Item
      - name: Check for Azure Boards Work Item
        env:
          AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
          AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          # Instalar o curl (se necessário)
          sudo apt-get update && sudo apt-get install -y curl jq

          # Obter o número do PR
          PR_NUMBER=$(jq -r '.pull_request.number' < $GITHUB_EVENT_PATH)

          # Obter os commits do PR
          COMMITS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/commits")

          # Verificar se há referência a um Work Item nos commits
          WORK_ITEM_FOUND=false
          for commit in $(echo "$COMMITS" | jq -r '.[].commit.message'); do
            if [[ $commit =~ AB#[0-9]+ ]]; then
              WORK_ITEM_FOUND=true
              break
            fi
          done

          if [ "$WORK_ITEM_FOUND" = false ]; then
            echo "No Azure Boards Work Item linked to this PR."
            exit 1
          fi

          echo "Azure Boards Work Item found in commit messages."
