name: Check Azure Boards Work Item - automatic

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-work-item-automatic:
    runs-on: ubuntu-latest

    steps:
      # Verificar se o PR está vinculado a um Work Item válido
      - name: Validate Azure Boards Work Item
        env:
          AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
          AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          GITHUB_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # Instalar o curl e jq (se necessário)
          sudo apt-get update && sudo apt-get install -y curl jq

          # Função para verificar os Work Items vinculados
          check_work_items() {
            curl -s -u :$AZURE_DEVOPS_PAT \
              "https://dev.azure.com/$AZURE_DEVOPS_ORG/$AZURE_DEVOPS_PROJECT/_apis/git/pullRequests?searchCriteria.repositoryId=$GITHUB_REPO&searchCriteria.pullRequestId=$PR_NUMBER&api-version=7.0" | \
              jq -r '.value[0].workItemRefs[]?.id'
          }

          # Tentar verificar os Work Items com retries
          MAX_RETRIES=5
          RETRY_DELAY=10
          for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i of $MAX_RETRIES to check for linked work items..."
            WORK_ITEMS=$(check_work_items)

            if [ -n "$WORK_ITEMS" ]; then
              echo "Work Items linked to this Pull Request: $WORK_ITEMS"
              exit 0
            fi

            echo "No work items found. Retrying in $RETRY_DELAY seconds..."
            sleep $RETRY_DELAY
          done

          echo "No Azure Boards Work Item linked to this Pull Request after $MAX_RETRIES attempts."
          exit 1
