name: Check Azure Boards Work Item - linked

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-work-item:
    runs-on: ubuntu-latest

    steps:
      # Verificar se o PR está vinculado a um Work Item válido
      - name: Validate Azure Boards Development Link
        env:
          AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
          AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          GITHUB_REPO: ${{ github.repository }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          # Instalar o curl e jq (se necessário)
          sudo apt-get update && sudo apt-get install -y curl jq

          # Obter todos os Work Items no projeto
          WORK_ITEMS=$(curl -s -u :$AZURE_DEVOPS_PAT \
            "https://dev.azure.com/$AZURE_DEVOPS_ORG/$AZURE_DEVOPS_PROJECT/_apis/wit/wiql?api-version=7.0" \
            -H "Content-Type: application/json" \
            -d '{
              "query": "SELECT [System.Id] FROM WorkItems WHERE [System.TeamProject] = @project"
            }' | jq -r '.workItems[].id')

          if [ -z "$WORK_ITEMS" ]; then
            echo "No work items found in the Azure Boards project."
            exit 1
          fi

          # Verificar se algum Work Item possui o PR como Development Link
          PR_FOUND=false
          for WORK_ITEM_ID in $WORK_ITEMS; do
            LINKS=$(curl -s -u :$AZURE_DEVOPS_PAT \
              "https://dev.azure.com/$AZURE_DEVOPS_ORG/$AZURE_DEVOPS_PROJECT/_apis/wit/workitems/$WORK_ITEM_ID?api-version=7.0" | \
              jq -r '.relations[]? | select(.rel == "ArtifactLink") | .url')

            for LINK in $LINKS; do
              if [[ "$LINK" == *"$PR_URL"* ]]; then
                echo "Pull Request $PR_URL is linked to Work Item $WORK_ITEM_ID."
                PR_FOUND=true
                break 2
              fi
            done
          done

          if [ "$PR_FOUND" = false ]; then
            echo "No Azure Boards Work Item linked to this Pull Request."
            exit 1
          fi
